 // --- 1. AI SPEECH FUNCTIONS ---
        
        function speak(text, callback) {
            // Cancel current speech
            window.speechSynthesis.cancel();
            
            const msg = new SpeechSynthesisUtterance();
            msg.text = text;
            msg.volume = 1;
            msg.rate = 1;
            msg.pitch = 1.1;

            // Visual effect on avatar
            const avatar = document.querySelector('.ai-avatar'); // Select visible avatar
            if(avatar) avatar.classList.add('speaking');

            msg.onend = function() {
                if(avatar) avatar.classList.remove('speaking');
                if (callback) callback();
            };

            window.speechSynthesis.speak(msg);
        }

        // --- 2. LOGIC FLOW ---

        function activateAI() {
            // Browser requires interaction to play audio.
            document.getElementById('step-1').classList.replace('visible', 'hidden');
            document.getElementById('step-2').classList.replace('hidden', 'visible');
            document.getElementById('step-2').classList.add('visible');

            // AI asks the question
            const avatar = document.getElementById('avatar-2');
            avatar.classList.add('speaking');
            
            speak("Happy Birthday! It is a special day. What is the name of the birthday person?", function() {
                avatar.classList.remove('speaking');
                document.getElementById('nameInput').focus();
            });
        }

        function handleEnter(e) {
            if(e.key === 'Enter') submitName();
        }

        function submitName() {
            const name = document.getElementById('nameInput').value.trim();
            if(!name) return;

            // Switch to party screen
            document.getElementById('step-2').classList.replace('visible', 'hidden');
            document.getElementById('step-3').classList.replace('hidden', 'visible');
            document.getElementById('step-3').classList.add('visible');
            document.getElementById('finalName').innerText = name;

            // Start Celebration
            startConfetti();
            
            // 1. Start Music (Generated by Code)
            playHappyBirthdayMusic();

            // 2. AI Speaks over music
            setTimeout(() => {
                speak(`Happy Birthday to you, ${name}! Wishing you a fantastic year ahead!`);
            }, 1000); // Wait 1 second for music intro
        }

        // --- 3. MUSIC SYNTHESIZER (Web Audio API) ---
        // This generates the "Happy Birthday" song code-side. No MP3 needed.
        
        const audioCtx = new (window.AudioContext || window.webkitAudioContext)();

        function playNote(frequency, startTime, duration) {
            const osc = audioCtx.createOscillator();
            const gainNode = audioCtx.createGain();

            osc.type = 'sine'; // Smooth sound (flute-like)
            osc.frequency.value = frequency;

            // Volume envelope (fade out)
            gainNode.gain.setValueAtTime(0.3, startTime);
            gainNode.gain.exponentialRampToValueAtTime(0.01, startTime + duration - 0.1);

            osc.connect(gainNode);
            gainNode.connect(audioCtx.destination);

            osc.start(startTime);
            osc.stop(startTime + duration);
        }

        function playHappyBirthdayMusic() {
            if(audioCtx.state === 'suspended') audioCtx.resume();

            const now = audioCtx.currentTime;
            
            // Notes frequencies (C Major)
            const C4=261.6, D4=293.7, E4=329.6, F4=349.2, G4=392.0, A4=440.0, B4=493.9, C5=523.3;

            // The Melody
            const notes = [
                {freq: C4, time: 0, dur: 0.4},
                {freq: C4, time: 0.5, dur: 0.4},
                {freq: D4, time: 1.0, dur: 0.8},
                {freq: C4, time: 2.0, dur: 0.8},
                {freq: F4, time: 3.0, dur: 0.8},
                {freq: E4, time: 4.0, dur: 1.6}, // "You"

                {freq: C4, time: 6.0, dur: 0.4},
                {freq: C4, time: 6.5, dur: 0.4},
                {freq: D4, time: 7.0, dur: 0.8},
                {freq: C4, time: 8.0, dur: 0.8},
                {freq: G4, time: 9.0, dur: 0.8},
                {freq: F4, time: 10.0, dur: 1.6}, // "You"
            ];

            notes.forEach(n => {
                playNote(n.freq, now + n.time, n.dur);
            });
        }

        // --- 4. CONFETTI EFFECT ---
        function startConfetti() {
            const canvas = document.getElementById('confetti-canvas');
            const ctx = canvas.getContext('2d');
            canvas.width = window.innerWidth;
            canvas.height = window.innerHeight;

            const pieces = [];
            const colors = ['#f00', '#0f0', '#00f', '#ff0', '#0ff'];

            for(let i=0; i<200; i++) {
                pieces.push({
                    x: Math.random() * canvas.width,
                    y: Math.random() * canvas.height - canvas.height,
                    w: Math.random() * 10 + 5,
                    h: Math.random() * 10 + 5,
                    color: colors[Math.floor(Math.random() * colors.length)],
                    speed: Math.random() * 3 + 2,
                    angle: Math.random() * Math.PI * 2
                });
            }

            function draw() {
                ctx.clearRect(0,0, canvas.width, canvas.height);
                pieces.forEach(p => {
                    ctx.fillStyle = p.color;
                    ctx.save();
                    ctx.translate(p.x, p.y);
                    ctx.rotate(p.angle);
                    ctx.fillRect(-p.w/2, -p.h/2, p.w, p.h);
                    ctx.restore();
                    p.y += p.speed;
                    p.angle += 0.1;
                    if(p.y > canvas.height) p.y = -20;
                });
                requestAnimationFrame(draw);
            }
            draw();
        }